# name: 🚀 Deploy Next.js to VPS (Corrected Strategy)
name: 🚀 Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            cd /home/austinosaz/pantherweb/pantherarestlounge

            git pull origin main

            npm install

            npm run build

            pm2 restart panthera-app

            pm2 save
